[package]
name = "chorus-client"
version = "0.1.0"
authors = ["Lukas Bachschwell <lukas@lbsfilm.at>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
